server:
  port: 8080
  servlet:
    context-path: /springsecuritylearning


spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/springsecuritylearning?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      min-idle: 1
      max-active: 20
      max-wait: 60000